name: Test déploiement

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test déploiement
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Utiliser Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Installer les dépendences
        working-directory: angular
        run: npm ci
      - name: Tester le build du site
        working-directory: angular
        run: npm run build
      - name: Lint
        working-directory: angular
        run: npm run lint
